/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface UserAccount {
  userId: string;
  username: string;
  email: string;
  fullName: string;
  avatarUrl: string;
  role: 'admin' | 'author' | 'reader';
}

export interface Author {
  userId: string;
  name: string;
  avatarUrl: string;
}

export interface Category {
  categoryId: string;
  name: string;
}

export interface Comment {
  commentId: string;
  userId?: string;
  userName: string;
  userAvatar?: string;
  text: string;
  createdAt: string; // ISO Date String
}

export interface Metrics {
  views: number;
  likes: number;
  shares: number;
}

export interface PostDocument {
  _id?: string; // Auto-generated by MongoDB ObjectId
  title: string;
  slug: string;
  content: string;
  excerpt: string;
  status: 'published' | 'draft';
  createdAt: string; // ISO Date String
  author: Author;
  category: Category;
  tags: string[];
  metrics: Metrics;
  recent_comments: Comment[]; // Embedded recent comments (Subset Pattern)
}

export interface QueryLog {
  id: string;
  timestamp: string;
  operation: string; // e.g. "db.Posts.find"
  query: string; // Formatted query string
  resultCount: number;
  executionTimeMs: number;
}

export interface AggregationResult {
  _id: string; // Category name
  totalPosts: number;
  totalViews: number;
  averageLikes: number;
}
